### PR TITLE
Updates AFNetworking dependency to 3.0

### PR DESCRIPTION
**Pull request by dzenbot**

### CODE REVIEW

**Comment by cameronehrlich** [comment]
Why is this not getting merged?

**Comment by cameronehrlich** [comment]
I realized that was a stupid comment about three seconds after I left the page... haha my bad.

**Comment by ikovalisko** [comment]
@dzenbot are you going to proceed with this PR?

**Comment by beloso** [comment]
@dzenbot @kcharwood Is this still planned to be merged?

**Pull request merged**
